version: 2.1

executors:
  python-executor:
    docker:
      - image: circleci/python:3.12
    working_directory: ~/repo

jobs:
  python-job:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Set up venv
          command: |
            python -m venv venv
            . venv/bin/activate
      - run:
          name: Install dependencies
          command: |
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            pytest --html=./report/report.html --self-contained-html --junitxml=./test-results/results.xml
      - store_test_results:
          path: ./test-results
      - store_artifacts:
          path: ./report.html
          destination: python-report

workflows:
  version: 2
  build-and-test:
    jobs:
      - python-job
