version: 2.1

executors:
  python-executor:
    docker:
      - image: circleci/python:3.10.1-node-browsers  # Change Python version to a supported one
    working_directory: ~/repo

jobs:
  python-job:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: set up venv
          command: |
            python -m venv venv && source venv/bin/activate && pip install -r requirements.txt
      - run:
          name: run tests
          command: |
            source venv/bin/activate && pytest --html=./report/report.html --self-contained-html
      - store_artifacts:
          path: report/
          destination: python-report

workflows:
  build-and-test:
    jobs:
      - python-job
